### ISSUE TITLE
Root model content is updated but dynamic-directive have old data

### ISSUE THREAD

**Issue by NHenzen** [thgreasi/tg-dynamic-directive#1]
Hi,

If i change the root model the templates retain the old data.
##### Testcase:

[link to codepen!](http://codepen.io/nick-henzen/pen/vNzBXp)
click on the button and the items are renamed to elements
##### Usecase:

I have a "template editor" with multiple pages.
in this editor we can add items and change order by dragging and dropping.
these items can also be nested.
i switch between pages bij changing the content of my model

Thanks,

**Comment by thgreasi** [comment]
Nice catch :+1: I will investigate it as soon as a find some time. Thanks for your detailed bug report & feedback.

**Comment by thgreasi** [comment]
Just pushed v0.4.0. Can you test that it works for you?

**Comment by NHenzen** [comment]
With the new version the content changes
Thank you for the fix.
